title Máquina Vending
|Proveedor|
|Administrador|
|Reponedor|
|Cliente|
|Administrador|
start
:Encargar golosinas;
|Proveedor|
:Enviar golosinas;
|Reponedor|
:Recibir golosinas;
:Reponer golosinas;
|Cliente|
:Comprar golosinas;
stop
